# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 261)
        MainWindow.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
"SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(102, 115, 140, 255),stop:1 rgba(56, 63, 77, 255));\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QLabel::disabled\n"
"{\n"
"    background-color: transparent;\n"
"    color: #898988;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar\n"
"{\n"
"    background-color: #484c58;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #898988;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background-color: #c4c5c3;\n"
"    color: #000000;\n"
"    border: 1px solid #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background-color: #979796;\n"
"    border: 1px solid #000;\n"
"    margin-bottom: -1px;\n"
"    padding-bottom: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #c4c5c3;\n"
"    border: 1px solid;\n"
"    color: #000000;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 1px;\n"
"    background-color: #363942;\n"
"    color: #ffffff;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    min-width : 150px;\n"
"    padding: 3px 20px 3px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #363942;\n"
"    color: #ffffff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #898988;\n"
"}\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"    background-color: #bbbcba;\n"
"    color: #000000;\n"
"    border-color: #051a39;\n"
"    border : 1px solid #000000;\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:0.486, y1:0, x2:0.505, y2:1, stop:0.00480769 rgba(170, 0, 0, 255),stop:1 rgba(122, 0, 0, 255));\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #9c0000;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #880000;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 3px;\n"
"    border-color: #000000;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(177, 181, 193, 255),stop:1 rgba(159, 163, 174, 255));\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #9fa3ae;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #7b7e86;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 3px;\n"
"    border-color: #000000;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(118, 118, 118, 255),stop:1 rgba(70, 70, 70, 255));\n"
"    border: 1px solid #333333;\n"
"    border-radius: 3px;\n"
"    padding-left: 6px;\n"
"    color: lightgray;\n"
"    font-weight: bold;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: #646464;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #979796;\n"
"    color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #c4c5c3;\n"
"    color: #000000;\n"
"    border: 1px solid black;\n"
"    selection-background-color: #363942;\n"
"    selection-color: #ffffff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; \n"
"    border-top-right-radius: 3px; \n"
"    border-bottom-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox, \n"
"QDoubleSpinBox,\n"
"QDateTimeEdit\n"
"{\n"
"    background-color: #000000;\n"
"    color: #00ff00;\n"
"    font-weight: bold;\n"
"    border: 1px solid #333333;\n"
"    padding : 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox:hover, \n"
"QDoubleSpinBox::hover,\n"
"QDateTimeEdit::hover\n"
"{\n"
"    border: 1px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button,\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(118, 118, 118, 255),stop:1 rgba(70, 70, 70, 255));\n"
"    border: 0px solid #333333;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::disabled, \n"
"QDoubleSpinBox::disabled,\n"
"QDateTimeEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover\n"
"{\n"
"    background-color: #646464;\n"
"    border: 1px solid #333333;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:disabled, QSpinBox::down-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::down-button:disabled,\n"
"QDateTimeEdit::up-button:disabled, QDateTimeEdit::down-button:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed,\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button::pressed,\n"
"QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button::pressed\n"
"{\n"
"    background-color: #979796;\n"
"    border: 1px solid #444444;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDoubleSpinBox::down-arrow,\n"
"QDateTimeEdit::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDoubleSpinBox::up-arrow,\n"
"QDateTimeEdit::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #000000;\n"
"    color: #00ff00;\n"
"    font-weight: bold;\n"
"    border: 1px solid #333333;\n"
"    padding: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"    border: 1px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-width: 1px;\n"
"    border-color: #051a39;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTextEdit-----*/\n"
"QTextEdit\n"
"{\n"
"    background-color: #808080;\n"
"    color: #fff;\n"
"    border: 1px groove #333333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTextEdit::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px groove #333333;\n"
"    border-radius: 2px;\n"
"    margin-top: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:0.486, y1:0, x2:0.505, y2:1, stop:0.00480769 rgba(170, 169, 169, 255),stop:1 rgba(122, 122, 122, 255));\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(71, 75, 87, 255),stop:1 rgba(35, 37, 43, 255));\n"
"    color: #ffffff;\n"
"    border: 2px groove #333333;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox{\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 2px solid #222222;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(://checkbox.png);\n"
"    border: 2px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 2px solid #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton{\n"
"    background-color: transparent;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked\n"
"{ \n"
"    border: 2px inset #222222; \n"
"    border-radius: 6px; \n"
"    background-color:  #323232;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover\n"
"{ \n"
"    border: 2px solid #00ff00; \n"
"    border-radius: 5px; \n"
"    background-color:  #323232;\n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked\n"
"{ \n"
"    border: 2px inset #222222; \n"
"    border-radius: 5px; \n"
"    background-color: #00ff00; \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 2px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTableView & QTableWidget-----*/\n"
"QTableView\n"
"{\n"
"    background-color: #808080;\n"
"    border: 1px groove #333333;\n"
"    color: #f0f0f0;\n"
"    font-weight: bold;\n"
"    gridline-color: #333333;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::disabled\n"
"{\n"
"    background-color: #242526;\n"
"    border: 1px solid #32414B;\n"
"    color: #656565;\n"
"    gridline-color: #656565;\n"
"    outline : 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:hover \n"
"{\n"
"    background-color: #484c58;\n"
"    color: #f0f0f0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected \n"
"{\n"
"    background-color: #484c58;\n"
"    border: 2px groove #00ff00;\n"
"    color: #F0F0F0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableView::item:selected:disabled\n"
"{\n"
"    background-color: #1a1b1c;\n"
"    border: 2px solid #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: #282830;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #282830;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"    text-align: left;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: #00ff00;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked:disabled\n"
"{\n"
"    color: #656565;\n"
"    background-color: #525251;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabWidget-----*/\n"
"QTabBar::tab\n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    height: 15px;\n"
"    width:160px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QTabBar::tab:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    border: 1px groove #333333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: #484c58;\n"
"    color: #ffffff;\n"
"    border: 1px groove #333333;\n"
"    border-bottom: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    background-color: #a3a7b2;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    background-color: #484c58;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:!selected \n"
"{\n"
"    margin-top: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:!selected \n"
"{\n"
"    margin-bottom: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"{\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:selected \n"
"{\n"
"    border-bottom-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:bottom:selected \n"
"{\n"
"    border-top-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
"{\n"
"    margin-right: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:!selected \n"
"{\n"
"    margin-right: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    margin-left: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"{\n"
"    min-height: 15ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:selected \n"
"{\n"
"    border-left-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:right:selected \n"
"{\n"
"    border-right-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"{\n"
"    margin-bottom: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
"QSlider{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:1, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000; \n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0, x2:1, y2:1, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000; \n"
"    width: 12px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #808080;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:vertical \n"
"{\n"
"    background-color: transparent;\n"
"    width: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0.483, x2:1, y2:0.517, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical \n"
"{\n"
"    background-color: #404040;\n"
"    border: 1px solid #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical \n"
"{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0.483, x2:1, y2:0.517, stop:0.00480769 rgba(201, 201, 201, 255),stop:1 rgba(72, 72, 72, 255));\n"
"    border: 1px solid #000;\n"
"    height: 12px;\n"
"    margin-left: -6px;\n"
"    margin-right: -6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:hover \n"
"{\n"
"    background-color: #808080;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:vertical:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:vertical:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDial-----*/\n"
"QDial\n"
"{\n"
"    background-color: #600000;\n"
"\n"
"}\n"
"\n"
"\n"
"QDial::disabled\n"
"{\n"
"    background-color: #404040;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #63676d;\n"
"    height: 18px;\n"
"    margin: 0px 18px 0 18px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: #a6acb3;\n"
"    border: 1px solid #656565;\n"
"    border-radius: 2px;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    width: 18px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    width: 18px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-right.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-left.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #63676d;\n"
"    width: 18px;\n"
"    margin: 18px 0 18px 0;\n"
"    border: 1px solid #222222;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #a6acb3;\n"
"    border: 1px solid #656565;\n"
"    border-radius: 2px;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    height: 18px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    border: 1px solid #1b1b19;\n"
"    background-color: #a6acb3;\n"
"    height: 18px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    background-color: #000;\n"
"    color: #00ff00;\n"
"    font-weight: bold;\n"
"    border: 0px groove #000;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"    border: 1px solid #000;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #ffaf02;\n"
"    border: 0px;\n"
"    border-radius: 10px;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #333;\n"
"    border: 0px;\n"
"    border-radius: 10px;\n"
"    color: #656565;\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(102, 115, 140, 255),stop:1 rgba(56, 63, 77, 255));\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.kloc_label = QtWidgets.QLabel(self.tab_0)
        self.kloc_label.setObjectName("kloc_label")
        self.gridLayout_5.addWidget(self.kloc_label, 0, 0, 1, 1)
        self.kloc_entry = QtWidgets.QLineEdit(self.tab_0)
        self.kloc_entry.setObjectName("kloc_entry")
        self.gridLayout_5.addWidget(self.kloc_entry, 0, 1, 1, 1)
        self.mode_label = QtWidgets.QLabel(self.tab_0)
        self.mode_label.setObjectName("mode_label")
        self.gridLayout_5.addWidget(self.mode_label, 1, 0, 1, 1)
        self.mode_cb = QtWidgets.QComboBox(self.tab_0)
        self.mode_cb.setObjectName("mode_cb")
        self.mode_cb.addItem("")
        self.mode_cb.addItem("")
        self.mode_cb.addItem("")
        self.gridLayout_5.addWidget(self.mode_cb, 1, 1, 1, 1)
        self.salary_label = QtWidgets.QLabel(self.tab_0)
        self.salary_label.setObjectName("salary_label")
        self.gridLayout_5.addWidget(self.salary_label, 2, 0, 1, 1)
        self.salary_entry = QtWidgets.QLineEdit(self.tab_0)
        self.salary_entry.setObjectName("salary_entry")
        self.gridLayout_5.addWidget(self.salary_entry, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout.setObjectName("gridLayout")
        self.data_label = QtWidgets.QLabel(self.tab_1)
        self.data_label.setObjectName("data_label")
        self.gridLayout.addWidget(self.data_label, 2, 0, 1, 1)
        self.cplx_label = QtWidgets.QLabel(self.tab_1)
        self.cplx_label.setObjectName("cplx_label")
        self.gridLayout.addWidget(self.cplx_label, 3, 0, 1, 1)
        self.rely_label = QtWidgets.QLabel(self.tab_1)
        self.rely_label.setObjectName("rely_label")
        self.gridLayout.addWidget(self.rely_label, 0, 0, 1, 1)
        self.rely_cb = QtWidgets.QComboBox(self.tab_1)
        self.rely_cb.setObjectName("rely_cb")
        self.rely_cb.addItem("")
        self.rely_cb.addItem("")
        self.rely_cb.addItem("")
        self.rely_cb.addItem("")
        self.rely_cb.addItem("")
        self.gridLayout.addWidget(self.rely_cb, 0, 1, 1, 1)
        self.cplx_cb = QtWidgets.QComboBox(self.tab_1)
        self.cplx_cb.setObjectName("cplx_cb")
        self.cplx_cb.addItem("")
        self.cplx_cb.addItem("")
        self.cplx_cb.addItem("")
        self.cplx_cb.addItem("")
        self.cplx_cb.addItem("")
        self.gridLayout.addWidget(self.cplx_cb, 3, 1, 1, 1)
        self.data_cb = QtWidgets.QComboBox(self.tab_1)
        self.data_cb.setObjectName("data_cb")
        self.data_cb.addItem("")
        self.data_cb.addItem("")
        self.data_cb.addItem("")
        self.data_cb.addItem("")
        self.gridLayout.addWidget(self.data_cb, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.time_label = QtWidgets.QLabel(self.tab_2)
        self.time_label.setObjectName("time_label")
        self.gridLayout_2.addWidget(self.time_label, 0, 0, 1, 1)
        self.time_cb = QtWidgets.QComboBox(self.tab_2)
        self.time_cb.setObjectName("time_cb")
        self.time_cb.addItem("")
        self.time_cb.addItem("")
        self.time_cb.addItem("")
        self.gridLayout_2.addWidget(self.time_cb, 0, 1, 1, 1)
        self.stor_label = QtWidgets.QLabel(self.tab_2)
        self.stor_label.setObjectName("stor_label")
        self.gridLayout_2.addWidget(self.stor_label, 1, 0, 1, 1)
        self.stor_cb = QtWidgets.QComboBox(self.tab_2)
        self.stor_cb.setObjectName("stor_cb")
        self.stor_cb.addItem("")
        self.stor_cb.addItem("")
        self.stor_cb.addItem("")
        self.gridLayout_2.addWidget(self.stor_cb, 1, 1, 1, 1)
        self.virt_label = QtWidgets.QLabel(self.tab_2)
        self.virt_label.setObjectName("virt_label")
        self.gridLayout_2.addWidget(self.virt_label, 2, 0, 1, 1)
        self.virt_cb = QtWidgets.QComboBox(self.tab_2)
        self.virt_cb.setObjectName("virt_cb")
        self.virt_cb.addItem("")
        self.virt_cb.addItem("")
        self.virt_cb.addItem("")
        self.virt_cb.addItem("")
        self.gridLayout_2.addWidget(self.virt_cb, 2, 1, 1, 1)
        self.turn_label = QtWidgets.QLabel(self.tab_2)
        self.turn_label.setObjectName("turn_label")
        self.gridLayout_2.addWidget(self.turn_label, 3, 0, 1, 1)
        self.turn_cb = QtWidgets.QComboBox(self.tab_2)
        self.turn_cb.setObjectName("turn_cb")
        self.turn_cb.addItem("")
        self.turn_cb.addItem("")
        self.turn_cb.addItem("")
        self.turn_cb.addItem("")
        self.gridLayout_2.addWidget(self.turn_cb, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.acap_label = QtWidgets.QLabel(self.tab_3)
        self.acap_label.setObjectName("acap_label")
        self.gridLayout_3.addWidget(self.acap_label, 0, 0, 1, 1)
        self.acap_cb = QtWidgets.QComboBox(self.tab_3)
        self.acap_cb.setObjectName("acap_cb")
        self.acap_cb.addItem("")
        self.acap_cb.addItem("")
        self.acap_cb.addItem("")
        self.acap_cb.addItem("")
        self.acap_cb.addItem("")
        self.gridLayout_3.addWidget(self.acap_cb, 0, 1, 1, 1)
        self.aexp_label = QtWidgets.QLabel(self.tab_3)
        self.aexp_label.setObjectName("aexp_label")
        self.gridLayout_3.addWidget(self.aexp_label, 1, 0, 1, 1)
        self.aexp_cb = QtWidgets.QComboBox(self.tab_3)
        self.aexp_cb.setObjectName("aexp_cb")
        self.aexp_cb.addItem("")
        self.aexp_cb.addItem("")
        self.aexp_cb.addItem("")
        self.aexp_cb.addItem("")
        self.aexp_cb.addItem("")
        self.gridLayout_3.addWidget(self.aexp_cb, 1, 1, 1, 1)
        self.pcap_label = QtWidgets.QLabel(self.tab_3)
        self.pcap_label.setObjectName("pcap_label")
        self.gridLayout_3.addWidget(self.pcap_label, 2, 0, 1, 1)
        self.pcap_cb = QtWidgets.QComboBox(self.tab_3)
        self.pcap_cb.setObjectName("pcap_cb")
        self.pcap_cb.addItem("")
        self.pcap_cb.addItem("")
        self.pcap_cb.addItem("")
        self.pcap_cb.addItem("")
        self.pcap_cb.addItem("")
        self.gridLayout_3.addWidget(self.pcap_cb, 2, 1, 1, 1)
        self.vexp_label = QtWidgets.QLabel(self.tab_3)
        self.vexp_label.setObjectName("vexp_label")
        self.gridLayout_3.addWidget(self.vexp_label, 3, 0, 1, 1)
        self.vexp_cb = QtWidgets.QComboBox(self.tab_3)
        self.vexp_cb.setObjectName("vexp_cb")
        self.vexp_cb.addItem("")
        self.vexp_cb.addItem("")
        self.vexp_cb.addItem("")
        self.vexp_cb.addItem("")
        self.gridLayout_3.addWidget(self.vexp_cb, 3, 1, 1, 1)
        self.lexp_label = QtWidgets.QLabel(self.tab_3)
        self.lexp_label.setObjectName("lexp_label")
        self.gridLayout_3.addWidget(self.lexp_label, 4, 0, 1, 1)
        self.lexp_cb = QtWidgets.QComboBox(self.tab_3)
        self.lexp_cb.setObjectName("lexp_cb")
        self.lexp_cb.addItem("")
        self.lexp_cb.addItem("")
        self.lexp_cb.addItem("")
        self.lexp_cb.addItem("")
        self.gridLayout_3.addWidget(self.lexp_cb, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.modp_label = QtWidgets.QLabel(self.tab_4)
        self.modp_label.setObjectName("modp_label")
        self.gridLayout_4.addWidget(self.modp_label, 0, 0, 1, 1)
        self.modp_cb = QtWidgets.QComboBox(self.tab_4)
        self.modp_cb.setObjectName("modp_cb")
        self.modp_cb.addItem("")
        self.modp_cb.addItem("")
        self.modp_cb.addItem("")
        self.modp_cb.addItem("")
        self.modp_cb.addItem("")
        self.gridLayout_4.addWidget(self.modp_cb, 0, 1, 1, 1)
        self.tool_label = QtWidgets.QLabel(self.tab_4)
        self.tool_label.setObjectName("tool_label")
        self.gridLayout_4.addWidget(self.tool_label, 1, 0, 1, 1)
        self.tool_cb = QtWidgets.QComboBox(self.tab_4)
        self.tool_cb.setObjectName("tool_cb")
        self.tool_cb.addItem("")
        self.tool_cb.addItem("")
        self.tool_cb.addItem("")
        self.tool_cb.addItem("")
        self.tool_cb.addItem("")
        self.gridLayout_4.addWidget(self.tool_cb, 1, 1, 1, 1)
        self.sced_label = QtWidgets.QLabel(self.tab_4)
        self.sced_label.setObjectName("sced_label")
        self.gridLayout_4.addWidget(self.sced_label, 2, 0, 1, 1)
        self.sced_cb = QtWidgets.QComboBox(self.tab_4)
        self.sced_cb.setObjectName("sced_cb")
        self.sced_cb.addItem("")
        self.sced_cb.addItem("")
        self.sced_cb.addItem("")
        self.sced_cb.addItem("")
        self.sced_cb.addItem("")
        self.gridLayout_4.addWidget(self.sced_cb, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calc_button = QtWidgets.QPushButton(self.centralwidget)
        self.calc_button.setObjectName("calc_button")
        self.horizontalLayout.addWidget(self.calc_button)
        self.graph_button = QtWidgets.QPushButton(self.centralwidget)
        self.graph_button.setObjectName("graph_button")
        self.horizontalLayout.addWidget(self.graph_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.rely_cb.setCurrentIndex(2)
        self.cplx_cb.setCurrentIndex(2)
        self.data_cb.setCurrentIndex(1)
        self.virt_cb.setCurrentIndex(1)
        self.turn_cb.setCurrentIndex(1)
        self.acap_cb.setCurrentIndex(2)
        self.aexp_cb.setCurrentIndex(2)
        self.pcap_cb.setCurrentIndex(4)
        self.vexp_cb.setCurrentIndex(2)
        self.lexp_cb.setCurrentIndex(3)
        self.modp_cb.setCurrentIndex(4)
        self.tool_cb.setCurrentIndex(3)
        self.sced_cb.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COCOMO"))
        self.kloc_label.setText(_translate("MainWindow", "KLOC (общее количество строк кода)"))
        self.kloc_entry.setText(_translate("MainWindow", "25"))
        self.mode_label.setText(_translate("MainWindow", "Режим проекта"))
        self.mode_cb.setItemText(0, _translate("MainWindow", "Обычный"))
        self.mode_cb.setItemText(1, _translate("MainWindow", "Промежуточный"))
        self.mode_cb.setItemText(2, _translate("MainWindow", "Встроенный"))
        self.salary_label.setText(_translate("MainWindow", "Средняя зарплата"))
        self.salary_entry.setText(_translate("MainWindow", "65000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("MainWindow", "Общее"))
        self.data_label.setText(_translate("MainWindow", "DATA (размер базы данных)"))
        self.cplx_label.setText(_translate("MainWindow", "CPLX (сложность продукта)"))
        self.rely_label.setText(_translate("MainWindow", "RELY (требуемая надежность)"))
        self.rely_cb.setCurrentText(_translate("MainWindow", "Номинальный"))
        self.rely_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.rely_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.rely_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.rely_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.rely_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.cplx_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.cplx_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.cplx_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.cplx_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.cplx_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.data_cb.setItemText(0, _translate("MainWindow", "Низкий"))
        self.data_cb.setItemText(1, _translate("MainWindow", "Номинальный"))
        self.data_cb.setItemText(2, _translate("MainWindow", "Высокий"))
        self.data_cb.setItemText(3, _translate("MainWindow", "Очень высокий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Атрибуты ПО"))
        self.time_label.setText(_translate("MainWindow", "TIME (ограничение времени выполнения)"))
        self.time_cb.setItemText(0, _translate("MainWindow", "Номинальный"))
        self.time_cb.setItemText(1, _translate("MainWindow", "Высокий"))
        self.time_cb.setItemText(2, _translate("MainWindow", "Очень высокий"))
        self.stor_label.setText(_translate("MainWindow", "STOR (ограничение объема памяти)"))
        self.stor_cb.setItemText(0, _translate("MainWindow", "Номинальный"))
        self.stor_cb.setItemText(1, _translate("MainWindow", "Высокий"))
        self.stor_cb.setItemText(2, _translate("MainWindow", "Очень высокий"))
        self.virt_label.setText(_translate("MainWindow", "VIRT (изменчимость виртуальной машины)"))
        self.virt_cb.setItemText(0, _translate("MainWindow", "Низкий"))
        self.virt_cb.setItemText(1, _translate("MainWindow", "Номинальный"))
        self.virt_cb.setItemText(2, _translate("MainWindow", "Высокий"))
        self.virt_cb.setItemText(3, _translate("MainWindow", "Очень высокий"))
        self.turn_label.setText(_translate("MainWindow", "TURN (время реакции компьютера)"))
        self.turn_cb.setItemText(0, _translate("MainWindow", "Низкий"))
        self.turn_cb.setItemText(1, _translate("MainWindow", "Номинальный"))
        self.turn_cb.setItemText(2, _translate("MainWindow", "Высокий"))
        self.turn_cb.setItemText(3, _translate("MainWindow", "Очень высокий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Атрибуты компьютера"))
        self.acap_label.setText(_translate("MainWindow", "ACAP (способности аналитика)"))
        self.acap_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.acap_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.acap_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.acap_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.acap_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.aexp_label.setText(_translate("MainWindow", "AEXP (знание приложений)"))
        self.aexp_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.aexp_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.aexp_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.aexp_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.aexp_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.pcap_label.setText(_translate("MainWindow", "PCAP (способности программиста)"))
        self.pcap_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.pcap_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.pcap_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.pcap_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.pcap_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.vexp_label.setText(_translate("MainWindow", "VEXP (знание виртуальный машины)"))
        self.vexp_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.vexp_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.vexp_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.vexp_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.lexp_label.setText(_translate("MainWindow", "LEXP (знание языка программирования)"))
        self.lexp_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.lexp_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.lexp_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.lexp_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Атрибуты персонала"))
        self.modp_label.setText(_translate("MainWindow", "MODP (использование современных методов)"))
        self.modp_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.modp_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.modp_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.modp_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.modp_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.tool_label.setText(_translate("MainWindow", "TOOL (использование программных инструментов)"))
        self.tool_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.tool_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.tool_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.tool_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.tool_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.sced_label.setText(_translate("MainWindow", "SCED (требуемые сроки разработки)"))
        self.sced_cb.setItemText(0, _translate("MainWindow", "Очень низкий"))
        self.sced_cb.setItemText(1, _translate("MainWindow", "Низкий"))
        self.sced_cb.setItemText(2, _translate("MainWindow", "Номинальный"))
        self.sced_cb.setItemText(3, _translate("MainWindow", "Высокий"))
        self.sced_cb.setItemText(4, _translate("MainWindow", "Очень высокий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Атрибуты проекта"))
        self.calc_button.setText(_translate("MainWindow", "Рассчитать проект"))
        self.graph_button.setText(_translate("MainWindow", "Сравнение параметров"))
